apiVersion: apps/v1
kind: Deployment
metadata:
  name: vessel-microservice-deployment
  labels:
    app: fleet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleet-service
  template:
    metadata:
      labels:
        app: fleet-service
    spec:
      containers:
      - name: fleet-app
        image: ghcr.io/mkmd-systems1git/maritime-fleet-gitops:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
